((asm-mode . ((indent-tabs-mode . t)
              (tab-width . 8)
              (asm-comment-char . ?#)))
 (verilog-mode . ((indent-tabs-mode . nil)
                  (tab-width . 8)
                  (verilog-auto-newline . nil)
                  (verilog-auto-lineup . 'declarations)
                  (verilog-indent-level . 2)
                  (verilog-indent-level-behavioral . 2)
                  (verilog-indent-level-declaration . 2)
                  (verilog-indent-level-module . 2)
                  (verilog-indent-level-directive . 0)
                  (verilog-case-indent . 2)
                  (verilog-indent-lists . nil)
                  (verilog-cexp-indent . 2)
                  (verilog-auto-endcomments . nil)
                  (verilog-case-fold . nil)
                  (verilog-typedef-regexp . "_t$")
                  (verilog-auto-delete-trailing-whitespace . t)
                  (verilog-auto-inst-dot-name . nil)
                  (verilog-auto-inst-vector . nil)
                  (verilog-auto-inst-column . 0)
                  (verilog-auto-inst-sort . t)
                  (verilog-auto-wire-type . "wire")
                  (verilog-auto-wire-comment . nil))))
